### ISSUE TITLE
Firefox tab closing does not reset everything

### ISSUE THREAD

**Issue by NicktheNoOne** [2G2C/nanotrasen-simulator#15]
On the version of firefox I'm using [Version 91.12.0esr (64-bit)] I can close and open my tab without losing progress on everything EXCEPT for the "More Station Capacity" button which will reset to its default 5 but does not delete owned stations.

After I reopen the tab, I need to buy the same station capacity over again but with an increased cost per space upgrade

I am on "Microsoft Windows 10 Home" [Version 10.0.19044 Build 19044] and have been able to reproduce it consistently by using Ctrl+W and then Ctrl+Shift+T to close and then open a closed tab

![image](https://user-images.githubusercontent.com/110256517/183632039-08ffd1ee-1445-4a3a-bdca-aacc84bd9536.png)
![image](https://user-images.githubusercontent.com/110256517/183632331-9111bf80-c2c3-4dd8-98d2-3dc7ae297348.png)
![image](https://user-images.githubusercontent.com/110256517/183632154-9763c7d3-bd4f-4a4a-96a9-5c25f6514c8c.png)
![image](https://user-images.githubusercontent.com/110256517/183632202-4abe75ce-7aa2-4436-a315-dd9627fcfff7.png)

**Comment by Just-a-Unity-Dev** [comment]
Somewhat fixed by #16? Credits is still bugged, so I'd like for that to be fixed.

**Comment by Just-a-Unity-Dev** [comment]
Fully fixed by #32
