### ISSUE TITLE
Default Crew Wages Cause Revolt

### ISSUE THREAD

**Issue by NicktheNoOne** [2G2C/nanotrasen-simulator#37]
When starting a new game and buying a station, the crew will get restless after about 20-30 seconds. New players who don't know to fix this will have their only station revolt and have to go 500000c into debt, forcing a restart

**Comment by NicktheNoOne** [comment]
After trying again a few more times, it's not very consistent. I think it's a bug where the crew demand goes up to 20 on station buy instead of after a set time. Every time I buy a station it seems random when they ask for a raise

**Comment by NicktheNoOne** [comment]
I've seen that if the crew does ask for a raise, sometimes it can cause the station to not be profitable, causing the player to make negative money and go into debt at game start

**Comment by Just-a-Unity-Dev** [comment]
Think this can be fixed by making specific events require some minimum amount of uptime.

**Comment by Just-a-Unity-Dev** [comment]
Seems to be patched
